### ISSUE TITLE
[Version: 1.1.6] Not possible to save attachments (error message "Can not bind parameter(s)")

### ISSUE THREAD

**Issue by Nuk03** [cap-js/attachments#103]
Hi Team,

Trying to implement attachments out-of-the box functionality in our CAP application, we have configured Object Store in AWS as per SAP documentation: https://help.sap.com/docs/object-store/object-store-service-on-sap-btp/configure-object-store-to-use-amazon-simple-storage-service and we have updated the attachments plugin to the latest version (1.1.6) and also the dependencies as well and now having an error message "_Can not bind parameter(s)_" when saving the attachments.

**To Reproduce**
We have an Entity with the attachments as per described in the plugin documentation: https://github.com/cap-js/attachments#readme

`using { Attachments } from '@cap-js/attachments';`

`@odata.draft.bypass
@odata.draft.enabled
entity MyEntity: cuid, managed {   
...
...
...
attachments          : Composition of many Attachments;
}`

Actual dependencies:
`"dependencies": {
    "@cap-js/attachments": "^1.1.6",
    "@cap-js/change-tracking": "^1.0.7",
    "@sap-cloud-sdk/connectivity": "^3.20.0",
    "@sap-cloud-sdk/core": "^1.54.2",
    "@sap-cloud-sdk/http-client": "^3.20.0",
    "@sap-cloud-sdk/resilience": "^3.15.0",
    "@sap/cds": "^8",
    "@sap/cds-hana": "^2",
    "@sap/cds-odata-v2-adapter-proxy": "^1.9.7",
    "@sap/hana-client": "^2.20.22",
    "@sap/xssec": "^4.2.4",
    "express": "^4",
    "jwt-decode": "^4.0.0",
    "node-cron": "^3.0.3",
    "sap-cf-destconn": "^1.0.0"
  },`

UI5 Version version = 1.125.1

**Expected behavior**
Expected is the files being saved into S3 bucket.

**Screenshots**
Upload a file and press SAVE button
![image](https://github.com/user-attachments/assets/46880340-e0fe-4617-87fb-9c580f203368)

![image](https://github.com/user-attachments/assets/2bbea21e-9aa5-4748-a5c8-f450160b7f98)

![image](https://github.com/user-attachments/assets/e1e13a8a-6fd3-4e6b-9fab-0e43fa805c8a)

![image](https://github.com/user-attachments/assets/a76c891d-0e34-4f5f-9d9a-dcb8c6d7808b)

Console error:
`arg1:
Error: Can not bind parameter(s)\n    at Socket.<anonymous> (/home/user/projects/my-project/node_modules/@sap/hana-client/lib/index.js:53:13)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)\n    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17) {code: -20007, sqlState: 'HY000', query: 'UPSERT my_entity_atta…S ( ?, ?, ?, ?, ?, ?, ?, ? ) WITH PRIMARY KEY', values: Array(1), stack: 'Error: Can not bind parameter(s)\n    at Socke…Trampoline (node:internal/async_hooks:130:17)', …}
code:
'-20007'
query:
'UPSERT my_entity_attachments ( up__ID, filename, "MIMETYPE", content, url, ID, modifiedAt, modifiedBy ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ? ) WITH PRIMARY KEY'
sqlState:
'HY000'
values:
(1) [Array(8)]
message:
'Can not bind parameter(s)'
stack:
'Error: Can not bind parameter(s)\n    at Socket.<anonymous> (/home/user/projects/my-project/node_modules/@sap/hana-client/lib/index.js:53:13)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)\n    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)'
`

Could be this an existing bug from previous versions? I saw a very similar issue already explained in #93 related to 1.1.5 version. 

Thanks a lot,

**Comment by Nuk03** [comment]
Only failing when testing in Local, but working once is deployed. 

Thank you.
