### ISSUE TITLE
Cannot add custom fields/logic to Attachments entity

### ISSUE THREAD

**Issue by Zahlii** [cap-js/attachments#65]
```
using {Attachments} from '@cap-js/attachments';
// also using {Attahcment as BaseAttachments} and naming our entity Attachments : BaseAttachments same error


entity UIAttachments : Attachments {
    approvalStatus                  : Association to cdh.Status @readonly;
}

entity Bla {
  attachments                             : Composition of many UIAttachments;
}
```

Results in:

```
[cds] - ❗️Uncaught TypeError: Cannot read properties of undefined (reading 'xpr')
    at _addKeysToData (/Users/***/PycharmProjects/cockpit/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/utils/data.js:67:22)
    at _addKeysToData (/Users/***/PycharmProjects/cockpit/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/utils/data.js:69:12)
    at _addForeignKeys (/Users/***/PycharmProjects/cockpit/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/utils/data.js:159:5)
    at getData (/Users/***/PycharmProjects/cockpit/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/utils/data.js:284:5)
    at new ODataRequest (/Users/***/PycharmProjects/cockpit/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/ODataRequest.js:141:20)
    at /Users/***/PycharmProjects/cockpit/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/create.js:27:13
    at /Users/***/PycharmProjects/cockpit/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/okra/odata-server/core/Dispatcher.js:135:7
    at new Promise (<anonymous>)
    at Dispatcher._handle (/Users/***/PycharmProjects/cockpit/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/okra/odata-server/core/Dispatcher.js:134:12)
    at Dispatcher.dispatch (/Users/***/PycharmProjects/cockpit/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/okra/odata-server/core/Dispatcher.js:97:21) {
  id: '1350143',
  level: 'ERROR',
  timestamp: 1718184547532
}
```

**Comment by Zahlii** [comment]
I was able to work around this by simply extending the given Attachments entity:

```
extend Attachments with {
    approvalStatus                  : Association to cdh.Status @readonly;
}
```

**Comment by muskansethi1** [comment]
Hi @Zahlii,
I am not able to reproduce this error with the latest versions of the packages. Can you please confirm if this issue is still valid?

**Comment by jeevitha011** [comment]
As there is no reply, closing the issue. Please reopen the issue, if required.

Thanks.
